### ISSUE TITLE
AMD load does not work?

### ISSUE THREAD

**Issue by fluffynuts** [brijeshb42/monaco-vim#49]
Using the exact code from the AMD example in the README, I get the same issue I see when trying to integrate in my own amd-aware app:

```
Loading "vs/editor/common/controller/cursorTypeOperations" failed
```

The `cursorTypeOperations` script only lives in the `esm` variant of `monaco-editor`.

I see that cm_adapter.js specifically relies on the esm variant of monaco -- is there any chance that AMD usage can be restored?

Thanks

**Comment by sartak** [comment]
This is affecting me too.

**Comment by hugoruscitti** [comment]
me too :(

**Comment by brijeshb42** [comment]
![Screenshot_20200625_115831](https://user-images.githubusercontent.com/717550/85667428-331f3e00-b6db-11ea-9827-54cb3d434e4f.png)

I can see that `require`ing `vs/editor/common/controller/cursorTypeOperations` in console of official monaco demo (microsoft.github.io/monaco-editor). Does that not work for you ?

**Comment by brijeshb42** [comment]
```js
require.config({
    paths: {
        'monaco-vim': 'https://unpkg.com/monaco-vim@0.1.7/dist/monaco-vim.js',
    },
});
require(['monaco-vim'], function(MonacoVim) {
    const vim = MonacoVim.initVimMode(editor);
})
```

This works fine in monaco demo which uses AMD. You just need to set the correct path of `vs`.

**Comment by hugoruscitti** [comment]
I made a minimal example to reproduce the problem, i think the problem is due to the order in which monaco and monaco-vim are loaded by load.js only when i load monaco-vim.js from local (not with a url path):

- online: https://monaco-vim-49.surge.sh/
- repo: https://github.com/hugoruscitti/monaco-vim__issue_49

If a try to load monaco-vim.js from local, then the error show sometimes (note that some time loads
ok, but sometimes fails):

- https://monaco-vim-49.surge.sh/simple-case-with-random-bug.html

![image](https://user-images.githubusercontent.com/99183/85812115-2845c700-b736-11ea-849b-da256b99fae2.png)

But, if i use this code works every time:

```javascript
require.config({
	paths: {
		'vs': '../node-modules/monaco-editor/min/vs',
		'monaco-vim': 'monaco-vim' // local-file
	}
});

require(['vs/editor/editor.main'], function() {
	var editor = monaco.editor.create(document.getElementById('container'), {
		value: "..."
		language: 'javascript'
	});

        // Load monaco-vim after editor creation.
        // =============================

	require(['monaco-vim'], function(MonacoVim) {
		const vim = MonacoVim.initVimMode(editor);
	})
});
```

This is the link to the demo:

- https://monaco-vim-49.surge.sh/workaround-local-monaco-vim.html


Btw: If I load monaco-vim.js from a remote path it works, I estimate it does because the time it takes to my browser get the file delays the loading of monaco-vim, but I'm really guessing here.

Ah, one more thing ... I really appreciate your work, thank you very much for making monaco-vim and share it with us. Thanks!!
